#!/bin/ash
set -e

if [ -z "$CODEBUILD_S3_BUCKET" ]; then
  echo "CODEBUILD_S3_BUCKET must be set"
  exit 1;
fi

aws configure set s3.signature_version s3v4

if [ -n "$BITBUCKET_COMMIT" ]; then
  ci_env_prefix="BITBUCKET_"
  map_file="$BITBUCKET_REPO_OWNER-$BITBUCKET_REPO_SLUG-$BITBUCKET_COMMIT.json";
elif [ -n "$GITLAB_CI" ]; then
  # ci_env_prefix="CI_"
  map_file="$CI_PROJECT_NAMESPACE-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA.json";
fi

echo $CODEBUILD_S3_BUCKET;

aws s3api get-object \
  --bucket $CODEBUILD_S3_BUCKET \
  --key "$CODEBUILD_S3_MAP_PATH/$map_file" \
  _map_file;

artifacts_s3_arn=`jq -r -c '.artifacts.location' _map_file`;

artifacts_s3=`echo $artifacts_s3_arn | awk -F: '{print $6}'`
artifacts_s3_bucket=`echo $artifacts_s3 | cut -d '/' -f 1`;
artifacts_s3_key=`echo $artifacts_s3 | cut -d '/' -f 2-`;

mkdir _artifacts;
cd _artifacts;

echo "s3://$artifacts_s3_bucket/$artifacts_s3_key";
files=`aws s3 sync s3://$artifacts_s3_bucket/$artifacts_s3_key .`
echo $files;

is_zip="false"
num_files=`ls -1 | wc -l`

if [ num_files == "1" ]; then
  first_file=`ls | sort -n | head -1`
  file_type=`type $first_file`
  if [ $file_type == *"Zip"* ]; then
    is_zip="true"
    mv $first_file _pipeline.zip
  fi
fi

echo "Is this a zip file? " $is_zip
if [ $is_zip == "false" ]; then
  zip -r _pipeline.zip .
fi

echo "Final file list"
ls -al


aws s3api put-object \
  --body _pipeline.zip \
  --bucket $CODEPIPELINE_S3_BUCKET \
  --key $CODEPIPELINE_S3_ARCHIVE_KEY;
